import { ensureAutomationRun, getAutomationRun, updateAutomationRun } from "../db/automation-runs";
import { getTaskRuntimeOwnership } from "../db/runtime-ownership";
import { errorResponse, jsonResponse } from "../response";
import { setExecutionAutomationContext } from "../db/executions";
import type { Env } from "../types";

function text(v:unknown):string{return v==null?"":String(v).trim();}
function acceptedStatus(status:string):boolean{return ["ACCEPTED","RUNNING","SUCCESS","WARNING"].includes(status);}

export async function handleCheckAutomationRun(request:Request,env:Env,requestId:string):Promise<Response>{let b:any;try{b=await request.json();}catch{return errorResponse("INVALID_REQUEST","JSON body required",400,requestId);}const taskId=text(b.taskId),runDate=text(b.runDate),runSlot=text(b.runSlot)||"RUN_0800";if(!taskId||!runDate)return errorResponse("INVALID_REQUEST","taskId and runDate are required",400,requestId);const row=await getAutomationRun(env,taskId,runDate,runSlot);if(!row)return jsonResponse({ok:true,taskId,runDate,runSlot,status:"AVAILABLE",shouldAcquire:true},200,requestId);return jsonResponse({ok:true,taskId,runDate,runSlot,status:row.status,shouldAcquire:!acceptedStatus(row.status),executionId:row.execution_id,resultCode:row.result_code},200,requestId);}

export async function handleAutomationIntake(request:Request,env:Env,requestId:string):Promise<Response>{let b:any;try{b=await request.json();}catch{return errorResponse("INVALID_REQUEST","JSON body required",400,requestId);}const jobs=Array.isArray(b.jobs)?b.jobs:[];if(jobs.length!==1)return errorResponse("UNSUPPORTED_BATCH","Phase 6 intake accepts exactly one Task001 job",400,requestId);const job=jobs[0]||{},taskId=text(job.taskId),runDate=text(b.runDate),runSlot=text(b.runSlot)||"RUN_0800";if(taskId!=="task001_smartlink_order")return errorResponse("TASK_NOT_ALLOWED","Automation intake is currently enabled only for Task001",409,requestId);const owner=await getTaskRuntimeOwnership(env,taskId);if(owner?.runtime_owner!=="CLOUDFLARE")return errorResponse("TASK_RUNTIME_NOT_OWNED","Task001 production ownership is not CLOUDFLARE",409,requestId,{runtimeOwner:owner?.runtime_owner??null});
  const files=Array.isArray(b.files)?b.files:[];const fileKey=text(job.inputs?.[0]?.fileKey);const staged=files.find((f:any)=>text(f.fileKey)===fileKey);if(!staged)return errorResponse("INPUT_FILE_NOT_FOUND","Task001 staged input file was not supplied",400,requestId);
  const run=await ensureAutomationRun(env,{taskId,runDate,runSlot,automationId:text(b.automationId)||null,requestId:text(b.requestId)||requestId,sourceStartDate:text(job.sourceStartDate)||null,sourceEndDate:text(job.sourceEndDate)||null});
  if(acceptedStatus(run.status))return jsonResponse({success:true,result:run.status==="SUCCESS"?"ALREADY_SUCCESS":"ALREADY_ACCEPTED",acceptedCount:1,failedCount:0,jobs:[{success:true,result:run.status==="SUCCESS"?"ALREADY_SUCCESS":"ALREADY_ACCEPTED",taskId,runSlot,status:run.status,executionId:run.execution_id??""}]},200,requestId);
  const payload={executionMode:"PRODUCTION",automation:{automationId:text(b.automationId),runDate,runSlot,requestId:text(b.requestId)||requestId,sourceStartDate:text(job.sourceStartDate),sourceEndDate:text(job.sourceEndDate),stagedFile:{stagingObjectKey:text(staged.stagingObjectKey),fileName:text(staged.fileName),contentType:text(staged.contentType),contentLength:Number(staged.contentLength||0),sha256:text(staged.sha256)}}};
  const internalReq=new Request(new URL("/api/executions",request.url).toString(),{method:"POST",headers:{"Content-Type":"application/json",Authorization:request.headers.get("Authorization")||""},body:JSON.stringify({taskId,source:{type:"DESKTOP_BOT",reference:text(b.automationId)||run.automation_run_id},idempotencyKey:`AUTOMATION:${taskId}:${runDate}:${runSlot}:${text(b.requestId)||requestId}`,requestedBy:{type:"BOT",id:text(b.requestedBy)||"OPS_DESKTOP_BOT"},correlationId:text(b.requestId)||requestId,payload})});
  const {handleCreateExecution}=await import("./executions");const resp=await handleCreateExecution(internalReq,env,requestId);const out:any=await resp.clone().json().catch(()=>null);if(!resp.ok||!out?.executionId)return resp;await setExecutionAutomationContext(env,out.executionId,{runDate,runSlot,automationId:text(b.automationId)||null});await updateAutomationRun(env,taskId,runDate,runSlot,{status:"ACCEPTED",executionId:out.executionId,automationId:text(b.automationId)||null,requestId:text(b.requestId)||requestId,sourceStartDate:text(job.sourceStartDate)||null,sourceEndDate:text(job.sourceEndDate)||null});return jsonResponse({success:true,result:"ACCEPTED",acceptedCount:1,failedCount:0,jobs:[{success:true,result:"ACCEPTED",taskId,runSlot,status:"ACCEPTED",executionId:out.executionId,jobId:out.executionId}]},202,requestId);
}

export async function handleAutomationDryRun(request:Request,env:Env,requestId:string):Promise<Response>{
  let b:any;try{b=await request.json();}catch{return errorResponse("INVALID_REQUEST","JSON body required",400,requestId);}
  const jobs=Array.isArray(b.jobs)?b.jobs:[];
  if(jobs.length!==1)return errorResponse("UNSUPPORTED_BATCH","Phase 6 dry-run intake accepts exactly one Task001 job",400,requestId);
  const job=jobs[0]||{},taskId=text(job.taskId),runDate=text(b.runDate),runSlot=text(b.runSlot)||"RUN_0800";
  if(taskId!=="task001_smartlink_order")return errorResponse("TASK_NOT_ALLOWED","Automation dry run is currently enabled only for Task001",409,requestId);
  const files=Array.isArray(b.files)?b.files:[];const fileKey=text(job.inputs?.[0]?.fileKey);const staged=files.find((f:any)=>text(f.fileKey)===fileKey);
  if(!staged)return errorResponse("INPUT_FILE_NOT_FOUND","Task001 staged input file was not supplied",400,requestId);
  const payload={executionMode:"PRODUCTION_DRY_RUN",automation:{automationId:text(b.automationId),runDate,runSlot,requestId:text(b.requestId)||requestId,sourceStartDate:text(job.sourceStartDate),sourceEndDate:text(job.sourceEndDate),stagedFile:{stagingObjectKey:text(staged.stagingObjectKey),fileName:text(staged.fileName),contentType:text(staged.contentType),contentLength:Number(staged.contentLength||0),sha256:text(staged.sha256)}}};
  const internalReq=new Request(new URL("/api/executions",request.url).toString(),{method:"POST",headers:{"Content-Type":"application/json",Authorization:request.headers.get("Authorization")||""},body:JSON.stringify({taskId,source:{type:"DESKTOP_BOT",reference:text(b.automationId)||`DRY_RUN:${runDate}:${runSlot}`},idempotencyKey:`AUTOMATION_DRY_RUN:${taskId}:${runDate}:${runSlot}:${text(b.requestId)||requestId}`,requestedBy:{type:"BOT",id:text(b.requestedBy)||"OPS_DESKTOP_BOT"},correlationId:text(b.requestId)||requestId,payload})});
  const {handleCreateExecution}=await import("./executions");const resp=await handleCreateExecution(internalReq,env,requestId);const out:any=await resp.clone().json().catch(()=>null);if(!resp.ok||!out?.executionId)return resp;
  await setExecutionAutomationContext(env,out.executionId,{runDate,runSlot,automationId:text(b.automationId)||null});
  return jsonResponse({success:true,result:"DRY_RUN_ACCEPTED",acceptedCount:1,failedCount:0,jobs:[{success:true,result:"DRY_RUN_ACCEPTED",taskId,runSlot,status:"ACCEPTED",executionId:out.executionId,jobId:out.executionId}]},202,requestId);
}
